table-api.md updated
vijikarthi/flink-connectors-wiki pull request #3
Opened 2018-10-28 10:43 UTC by Aparnarr

Signed-off-by: Aparna <Aparna.Rr@emc.com>

1. Minor editions
2. Format fix.
3. Hyperlinks rendered

2018-10-28 17:34 UTC, vijikarthi requested changes

2018-10-28 17:34 UTC, vijikarthi commented on table-api.md
> +The following example of uses the provided table source to read JSON-formatted events from a Pravega Stream:
Please remove `of`

> The following example uses the provided table source to read JSON-formatted events from a Pravega Stream:

2018-10-29 11:18 UTC, Aparnarr commented on table-api.md
> +The following example of uses the provided table source to read JSON-formatted events from a Pravega Stream:
done

2018-10-29 20:56 UTC, vijikarthi approved these changes

2018-10-29 20:56 UTC, merged