Issue serialization
vijikarthi/flink-connectors-wiki pull request #4
Opened 2018-10-28 11:37 UTC by Aparnarr

Signed-off-by: Aparna <Aparna.Rr@emc.com>

1. Minor edits
 2. links included

2018-10-28 11:43 UTC, Aparnarr commented on serialization.md
> +Below is an example, to pass an instance of the appropriate Pravega de/serializer class to the adapter's constructor:
@vijay  The below statement should be only in the last line???? or can be moved to top line!..?

Note that the Pravega serializer must implement `java.io.Serializable` to be usable in a Flink program.

2018-10-28 17:26 UTC, vijikarthi requested changes

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
> +Its a common scenario to use Flink to process Pravega Stream data produced by a non-Flink application.  The Pravega client library used by such applications defines the [`io.pravega.client.stream.Ser
Please change the Pravega link to http://pravega.io/docs/latest/javadoc/clients/io/pravega/client/stream/Serializer.html

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
>  - [`org.apache.flink.streaming.util.serialization.SerializationSchema`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/util/serialization/Serializatio
Please change link to https://ci.apache.org/projects/flink/flink-docs-stable/api/java/org/apache/flink/streaming/util/serialization/SerializationSchema.html

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
>  - [`org.apache.flink.streaming.util.serialization.DeserializationSchema`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/util/serialization/Deserializ
Please change the link to https://ci.apache.org/projects/flink/flink-docs-stable/api/java/org/apache/flink/streaming/util/serialization/DeserializationSchema.html

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
> +- [`io.pravega.connectors.flink.serialization.PravegaSerializationSchema`](https://github.com/pravega/flink-connectors/blob/7971206038b51b3cf0e317e194c552c4646e5c20/src/main/java/io/pravega/connector
Please change the link to reflect the master branch
https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/serialization/PravegaSerializationSchema.java

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
> +- [`io.pravega.connectors.flink.serialization.PravegaDeserializationSchema`](https://github.com/pravega/flink-connectors/blob/7971206038b51b3cf0e317e194c552c4646e5c20/src/main/java/io/pravega/connect
Please change the link to reflect master branch

https://github.com/pravega/flink-connectors/blob/master/src/main/java/io/pravega/connectors/flink/serialization/PravegaDeserializationSchema.java

2018-10-28 17:26 UTC, vijikarthi commented on serialization.md
> +Below is an example, to pass an instance of the appropriate Pravega de/serializer class to the adapter's constructor:
Let it be there as-is i.e in the `Interoperability with Other Applications` section.

2018-10-29 11:05 UTC, Aparnarr commented on serialization.md
> +Below is an example, to pass an instance of the appropriate Pravega de/serializer class to the adapter's constructor:
ok

2018-10-29 11:07 UTC, Aparnarr commented on serialization.md
> +Its a common scenario to use Flink to process Pravega Stream data produced by a non-Flink application.  The Pravega client library used by such applications defines the [`io.pravega.client.stream.Ser
done

2018-10-29 11:13 UTC, Aparnarr commented on serialization.md
> +- [`io.pravega.connectors.flink.serialization.PravegaDeserializationSchema`](https://github.com/pravega/flink-connectors/blob/7971206038b51b3cf0e317e194c552c4646e5c20/src/main/java/io/pravega/connect
done

2018-10-29 11:13 UTC, Aparnarr commented on serialization.md
> +- [`io.pravega.connectors.flink.serialization.PravegaSerializationSchema`](https://github.com/pravega/flink-connectors/blob/7971206038b51b3cf0e317e194c552c4646e5c20/src/main/java/io/pravega/connector
done

2018-10-29 11:13 UTC, Aparnarr commented on serialization.md
>  - [`org.apache.flink.streaming.util.serialization.DeserializationSchema`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/util/serialization/Deserializ
done

2018-10-29 11:13 UTC, Aparnarr commented on serialization.md
>  - [`org.apache.flink.streaming.util.serialization.SerializationSchema`](https://ci.apache.org/projects/flink/flink-docs-release-1.3/api/java/org/apache/flink/streaming/util/serialization/Serializatio
done

2018-10-29 21:07 UTC, vijikarthi approved these changes

2018-10-29 21:07 UTC, merged